### ISSUE TITLE
ログインを正しく実装

### ISSUE THREAD

**Issue by KeisukeYamashita** [jphacks/TK_1711#52]
JPHACKS では本質的でなかったため放置した、ログインをちゃんと実装する。

**Comment by rinchsan** [comment]
Swiftからログイン・サインアップ用のAPIを叩く必要が出て来ると思うから、エンドポイントやパラメータが詳細に決まったらiOS側も実装します！
取り組むときに別Issueたてます

**Comment by KeisukeYamashita** [comment]
@snowman-mh tmp議論

iOSでバリデーションしてRailsで認証するのがベストやと思うけど、どうかな？

**Comment by KeisukeYamashita** [comment]
api設計優先的にやります！
いまのところ
`http://localhost/api/v1/user`にpostになると思うけど、また連絡する！

**Comment by rinchsan** [comment]
https://github.com/jphacks/TK_1711/issues/53 でも書いたけど、IDが整数値になってるかどうかのバリデーションは追加するべきやな
でもサーバでもDBにアクセスするんやしバリデーションはかけたほうが良いと思う。
あと、整数値のIDをユーザに覚えさせるのはどうかと思うけど、そこんとこどうやろう

**Comment by KeisukeYamashita** [comment]
Rails側でもバリデーションしよう！
IDがメールアドレスやったらOK?

**Comment by rinchsan** [comment]
うん、メアドなら良さそう

**Comment by KeisukeYamashita** [comment]
@snowman-mh 

仕様書

## login
エンドポイント:`api/v1/login`
メソッド：`POST`
パラメータ: `?email=hogehoge@gmail.com&password=hogehoge`

## Signup
エンドポイント:`api/v1/user/new`
メソッド：`POST`
パラメータ：`?email=hogehoge@gmail.com&password=hogehoge&password_confirmation=hogehoge`

## 共通
ただしくパラメータが渡せてない、DBに書き込みができない場合は
```
error : {
       message: "エラー内容`
}
```

が返ってくる。
通ると、今まで通り、containerとかbalanceが入ったやつが返ってくるので変更必要なし。
